language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nDmqrVnWoSYUgd/OGiMMINMWLxawRgRE0pSWRTwe8HnWUcNbuqkN/QkffCnwT8Whic2ss7ujQZGtDuUXAyyAiAu9P+4+aiPjxCgOGrNpwkpntQTvALtrhuSWaSqc2AlRYYd5AjXY1wiap2TNZs1phSxK/ohUXQRIoxFjsfXRR5wln2gxte4EJbbb65Ms+gP9fpfUkddlIcak6/NKH7pz7IxoSHaFsn4PFpj1V5rxiCitXJVS/t8xlyN/po4c3+t42LU2gz+AUjhycOkeebmGwMIS8lNRX1zVaGFxALPfi6Vb9E9IBNlSgBbjXiB8hdXbV7epnm3Xz8GL790Ch+lR8mNEBRm11AUF7JoglbMyIqVT3OBw90wf+GS4Oxjdy7Ig++ib5Kh+6Q8gOqNkT2bsjyH0iMAf46ymLO57w42jWiVRPOJcNXd2ZBW7DUw8X6Z41oI5WyWo1WtHFTKkoukK8+HqUCKu4FiFtErmIhKsjj9v/LVmZAUEatFCBBVR3Hep4FZa4RkTSL7vHSih5tA3uKpnK0Bno2YAe8TG4TfuP7ZiXLiOhaomCTiAwikD7MOUsvWe1D+8Qw73BbDWHrLRTR70RDXZoaFiX9jOf96U75Ov0G5tBQRJS2BV+0KItfrd6NFGd7XVLFyTW30sTHLPMFM+33YG5UYiPFt+7EXqoLE=
  app: rezolvd-api
  on:
    repo: staysee/rezolvd-api
